name: Build AX88179 Driver for Raspberry Pi 4B (OpenWrt 24.10)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential \
                                  libncurses5-dev \
                                  bc \
                                  flex \
                                  bison \
                                  libssl-dev \
                                  ccache \
                                  wget \
                                  unzip \
                                  zstd

      - name: Download OpenWrt SDK (Raspberry Pi 4B, 24.10)
        run: |
          mkdir openwrt-sdk
          cd openwrt-sdk
          wget https://downloads.openwrt.org/releases/24.10.0/targets/bcm27xx/bcm2711/openwrt-sdk-24.10.0-bcm27xx-bcm2711_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          tar -I zstd -xf openwrt-sdk-24.10.0-bcm27xx-bcm2711_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          echo "解压完成"
          

      - name: Set up environment variables
        run: |
          echo "export STAGING_DIR=$GITHUB_WORKSPACE/openwrt-sdk/staging_dir" >> $GITHUB_ENV
          echo "export PATH=$GITHUB_WORKSPACE/openwrt-sdk/staging_dir/toolchain-24.10.0-bcm27xx-bcm2711_gcc-13.3.0_musl/bin:$PATH" >> $GITHUB_ENV

      - name: Build AX88179 driver module
        run: |
          echo "$(pwd)"
          #cd $GITHUB_WORKSPACE
          export ARCH=arm64
          export CROSS_COMPILE=$GITHUB_WORKSPACE/openwrt-sdk/staging_dir/toolchain-24.10.0-bcm27xx-bcm2711_gcc-13.3.0_musl/bin/aarch64-openwrt-linux-
          export KERNELDIR=$(find $GITHUB_WORKSPACE/openwrt-sdk/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/ -name "linux-*" | head -n 1)
          cd ASIX_USB_NIC_Linux_Driver_Source_v3.4.0
          make -C $KERNELDIR M=$PWD modules

      - name: Upload built module
        uses: actions/upload-artifact@v4
        with:
          name: ax88179-driver
          path: "ASIX_USB_NIC_Linux_Driver_Source_v3.4.0/*.ko"
