name: Build kmod-usb-net-ax88179

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile kmod-usb-net-ax88179
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev \
          gawk git subversion libssl-dev gettext unzip zlib1g-dev file

    - name: Initialize feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install kmod-usb-net-ax88179

    - name: Configure build
      run: |
        make defconfig
        # 这里为了更保险起见，确保包含kmod-usb-net-ax88179
        echo "CONFIG_PACKAGE_kmod-usb-net-ax88179=m" >> .config

    - name: Download source and compile
      run: |
        make package/kernel/linux/compile V=s

    - name: Collect artifacts
      run: |
        mkdir -p output
        find bin/packages/ -name 'kmod-usb-net-ax88179*.ipk' -exec cp {} output/ \;

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: kmod-usb-net-ax88179
        path: output/
